language: go
sudo: required
go:
  - 1.6.3
  - 1.7.1
  - tip
install:
  - sudo add-apt-repository -y ppa:masterminds/glide && sudo apt-get update
  - sudo apt-get install -y glide
  - glide install
script: go test -v
matrix:
  allow_failures:
    - go: tip
